### ISSUE TITLE
[Home, pdf page 2] connect banner to ad account

### ISSUE THREAD

**Issue by ignacioch** [labooltd/GameAndroid#1]
Please use Admob. Email from them mentions :

Λοιπον για το admob: 

account: devineuf@gmail.com
Publisher ID: pub-1197998631655582

I think https://developers.google.com/admob/ this is where you get the SDK ...

**Comment by panagiotissp** [comment]
I had a look and tried to do the integration part with Admob, but it seems I'm stuck:
1. In the admob guide page https://firebase.google.com/docs/admob/android/quick-start
it has the step of "Integrate Firebase and the Mobile Ads SDK".
2. In the corresponding page (https://firebase.google.com/docs/android/setup) it says that I should add the Firebase into the app and there actually is the "Firebase Assistant" which is in the GUI of Android Studio and seems very simple to make the integration. 
However I have issues with the first step to 'Connect to Firebase' since it opens a gmail account to sign in.
Lastly, in the "manual process" of adding it (https://firebase.google.com/docs/android/setup#manually_add_firebase)
one should connect to Firebase console and actually download some files etc.

So, something seems to be missing and I cannot proceed with the integration of Admob.
Please have a look/contact customer asap.

**Comment by ignacioch** [comment]
We don't want to use Firebase, so I will try and do without that. Found that online but with a little bit more googling we can find more details.


. Instead of using the quick start on the AdMob page I used these instructions to set op google services:
https://developers.google.com/android/guides/setup

And then the ads service: "com.google.android.gms:play-services-ads:9.0.2"

So, let's start first without Firebase. If not possible, we will set up a Firebase account.

**Comment by panagiotissp** [comment]
So it works with the test ad by Google:
![screenshot_2017-03-22-01-46-51](https://cloud.githubusercontent.com/assets/14311142/24175902/90f19798-0ea1-11e7-87a2-6d7e7d35a440.png)

That means that the integration is successful.
So, as a last step, based on the steps described here https://firebase.google.com/docs/admob/android/quick-start

it seems that the ad unit IDs will finally be needed ("ad unit IDs have the form ca-app-pub-XXXXXXXXXXXXXXXX/NNNNNNNNNN") as long as the app ID ("App IDs have the form ca-app-pub-XXXXXXXXXXXXXXXX~NNNNNNNNNN.")

**Comment by ignacioch** [comment]
For admob, I have this :

account: devineuf@gmail.com
Publisher ID: pub-1197998631655582

That's  the one I am using in IOs. Again, do we need to set up a Firebase app? Ideally we would like to avoid that.

**Comment by ignacioch** [comment]
Again can we make it work with Admob- we want to avoid Firebase setup. Is it possible?

If we need Firebase and can't do without that, then let me know what you need. I am not using Firebase on IOS just admob SDK so ideally we should stick to the same.

**Comment by panagiotissp** [comment]
I'm putting here for more convenience 2 screenshots of an article showing what I mean:
<img width="526" alt="steps-admob1" src="https://user-images.githubusercontent.com/14311142/28976752-ce5b03ec-7947-11e7-9542-daf9a877c72d.PNG">
<img width="424" alt="steps-admob2" src="https://user-images.githubusercontent.com/14311142/28976753-ce70dec4-7947-11e7-8b29-4fc3eb04d32a.PNG">

These are from the following article: https://www.androidhive.info/2016/02/android-how-to-integrate-google-admob-in-your-app/

@ignacioch  please have a look to what I mean exactly, since this is one of the 2 most ambiguous things to me for the whole project (the other is the corresponding fb setup).

If you are not still sure about what I mean maybe a call would help both of us.

**Comment by ignacioch** [comment]
Panagioti, I still dont understand the issue here - 

1. clients should create the admob account - and they say they have already done it.

account: devineuf@gmail.com
Publisher ID: pub-1197998631655582

2. we should use admob sdk and integrate using the above account we have - i am using this on ios and it works with just the above credentials.

Does it work with Android? if not, you need to tell me what you want from them in order to work.

PS : If I get it correctly - and correct me if I am wrong.

1) you need the clients to follow the procedure above and give you back two ad units - on for banner and one for the full screen? I would tell them so, but is there anything else you  need?

I dont think there is anything ambiguous here - you can go on with creating an admob account with one of your emails ( or me creating a demo one for you ) and we just replace the tokens in the configuration once clients do theirs.

[ same apply for fb integration - i need you to tell me if what you have already does not work - we can use ones with our emails until we have the correct tokens from clients ]

**Comment by panagiotissp** [comment]
@ignacioch  I checked again.
Yes they need to create this Unit id thing.
I did it by creating an Admob account with my personal email as you suggested. And it is actually one of the steps of the process.

I created a test account with a test unit id and the add loaded. So, I suppose the current issue can be closed?
Anyway, Google says not to use real ad-units/ads with devices that are not explicitly put in the code as 'test devices'
_"However, once you register an app in the AdMob UI and create your own ad unit IDs for use in your app, you'll need to explicitly configure your device as a test device when you're developing. This is extremely important.
Testing with real ads (even if you never tap on them) is against AdMob policy and can cause your account to be suspended"_

Not sure when customer/you want to do this step. 
The instructions (https://developers.google.com/admob/android/test-ads#enable_test_devices) say to have logs of AndroidStudio open and check from there the device ID, so I'm not sure how the customers could send me their deviceID - in order to register it as 'test device' and use the actual ad-uni they will create in their Admob account.

From my perspective, I think this ticket can be closed, but I'm not sure if we should somehow take the extra step to register customer's device (or any other one) as test device to test the 'real thing' 

What do you think?

**Comment by ignacioch** [comment]
Ok, I am not sure I get it completely but we need to asnwer the following : 

- will the clients see the ads on their phone with the apk as it is now? if they need to send a device id and this needs to be registered somewhere, they will do it. They already have done it for apple devices.

- what changes do we need to do when going on prod?

- we need to make sure we know the steps needed, so that everything is done under their account in the end. we can use ours ( or yours ) for now, but when app is confirmed that is completed and we need to do the final setup, we need to tell them, you have to do these 3 steps, or follow this tutorial blah blah blah.

so yes, we can close the issue if you think the above questions have clear answers and we know what we have to do :)

**Comment by panagiotissp** [comment]
@ignacioch for my test account, I changed the 2 ids:
- the app_id
- the ad unit id (for the banner in the main menu page)

and that was it, it seemed to work with no issues at all.
(A note here as a reminder that there is only 1 ad unit id since there is only 1 ad shown in the whole app. A different ad unit id is required for each different banner that is shown in the app.)

So, these 2 ids are what is supposed to only be changed to go to production (along with removing the test device ids in the code of course, which are only for the development phase)

That's why from my point of view this issue can be closed, I supposedly do not have anything more to do.
It would be best though that the customer setup this and provide us with the app_id and the ad unit id, and also with their device id.
That way they would review the actual ad banner in their actual admob account, and the setup process will be complete for good.
The final deliverable is supposed to be 100% functional, and this includes the setup steps from customer's point of view too.

I'm closing this issue though. If it is decided to go along my suggestion, then you may reopen the current issue once we have the required ids.
