### ISSUE TITLE
[ Jokers ] +2 JOKER & 1 POINT JOKER animation suggestion

### ISSUE THREAD

**Issue by ignacioch** [labooltd/GameAndroid#110]
In order to simplify The "attacking joker +2" and the "defensive joker  1 point". When used, the points next to the answers could be modified on the page with the answers directly. Example: If the "1 point joker" is used, all answers give one point (except kotsana), that way "1" is written next to each answer, and on the "point bar" page there is no need for an extra animation.

**Comment by panagiotissp** [comment]
@ignacioch  this is already how it is supposed to be working.
* For "attacking +2" and "defensive 1" updated answer points are shown in Question page (and obviously calculated on Score page afterwards)
* For "multiply by 2" and "divide by 2" answer points **are not** changed in Question page UI, but are calculated of course in Score page (animation is done based on that etc)

I'm closing current issue since I do not see any inconsistency

**Comment by ignacioch** [comment]
Reopening. We need to provide the extra animation the client requests. I need to send a video to make it more clear how the animation works for each of the case.

**Comment by ignacioch** [comment]
but in words the animations for the x2 or /2 case is : 

you animate to the score without jokers. then text flashes ( you will see in the video ) and the score animates to the final score with the jokers.

Implementation wise we can discuss the ios approach if you think it's useful.
