### ISSUE TITLE
[GameSettingsP1 Page] Can teams have same color?

### ISSUE THREAD

**Issue by panagiotissp** [labooltd/GameAndroid#12]
Right now teams can have same color, e.g. if red is selected for team A then red is not disabled for the rest of the teams.
Is that right?

**Comment by ignacioch** [comment]
yes that's true. You can implement it any way you like :

A. disable the colour for rest of the teams
B. allow it but when the same colours are selected for 2 teams for example, then 'Next' button is greyed out. And there is a highlight on the teams that fail ( I will provide a screenshot ) if you go that route. 

If you have already implemented A, leave it as it is for now. IOS does B but not a high priority item for the time being. Only issue with A is that assuming I have selected a colour for all teams ( let's say 4 ) then I can't change colours right? Because every other color is disabled. I will need to go back and create a new game.

**Comment by panagiotissp** [comment]
No as I wrote right now this is allowed and I have not implemented anything on that since it was not included in the functionality provided initially.
So, if option B is the correct one there is no point to initially implement the option A and at some point to change back.

Send me whenever possible the corresponding screenshots and what exactly should be shown/highlighted, in what color, what the border size should be if a border is the kind of highlighting you are referring to, any text that may be shown in what fonts, etc. And I will implement it directly that way.

**Comment by ignacioch** [comment]
https://www.dropbox.com/s/uwf5cjvkz1wisy8/Photo%2023-03-2017%2C%2022%2020%2008.png?dl=0

https://www.dropbox.com/s/3cseabm1i5jfmfm/Photo%2023-03-2017%2C%2022%2020%2010.png?dl=0

**Comment by ignacioch** [comment]
The screenshots should be enough, if you have more questions do let me know.

**Comment by panagiotissp** [comment]
Logic of conflict among teams with same color selected added.
