### ISSUE TITLE
-In process- Missing graphics

### ISSUE THREAD

**Issue by panagiotissp** [labooltd/GameAndroid#30]
Please let's not discuss anything here until time comes. 

For now, I will just use this issue to leave comment for any graphics that are missing during the process of closing all other issues.

**Comment by panagiotissp** [comment]
- Newly provided Clock image for Question Page is wrong (too large) (related issue #27)

**Comment by panagiotissp** [comment]
Can you review this @ignacioch ?
I do not think there are (m)any more graphics that are missing (if sth occurs I will update the current issue of course)

If sth is not clear, it can always be clarified by checking the apk

**Comment by ignacioch** [comment]
As we said for the graphics, let's put the "bad" ones in the apk. We also need a final list of what graphics missing and send them that one.

**Comment by ignacioch** [comment]
update : they will review graphics on app and send what is needed.

**Comment by ignacioch** [comment]
OK communicating that is kind of tricky - and I have a lot of back and forth emails. To speed things up - can we put a bullet list on the description maybe with items we are missing and the dimensions we want them. Then we can easily tick /untick what we are missing /got.

**Comment by panagiotissp** [comment]
Ok yes @ignacioch  but we should take some decisions:
1) I will put in the app **whatever** graphics I have. This means though that pages will break, the demo experiecen will be really bad. BUT, only graphics will be the problem. We should communicate that.
E.g. the clock image on the Question Page is huge. If page breaks, I don't care. I will put the graphic in there, and put it also in the bulelt list you mentioned (It is already  in my comment above) and that's it from my side. Are we good with that?

2) I personally do not know the correct dimensions of the graphics. 
E.g. for the Clock image above, I will not be the one _selecting_ the dimensions. 
And I will not do the job of comparing images' dimensions among them, just in case I find sth that makes sense in order to propose that to the customer.
I think this is clear and agreed too, right?

Please let's agree on the 2 above and the next versions of tha apks will be with whatever graphics provided. There is no back to this though. So, next apk versions might be "ugly"/breaking UI (not sure how it will look like, really) until the correct graphics are provided.

Do you agree with that approach?

**Comment by ignacioch** [comment]
Ok regarding those 2:

1) let's leave what we have or empty - otherwise we might lose time from debugging until we get back the new ones. But let's keep the list here.

2) no sorry I didn't mean the exact clock dimensions.i meant the screen dimensions ( eg I am missing the clock for the xxdpi screen - screen size is 680x960). And client should give the correct clock for that screen size.

Is it more clear now?

Sent from my phone, Sorry for typos.

On 2 Nov 2017, at 20:22, Panagiotis Spirou <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok yes @ignacioch<https://github.com/ignacioch> but we should take some decisions:

  1.  I will put in the app whatever graphics I have. This means though that pages will break, the demo experiecen will be really bad. BUT, only graphics will be the problem. We should communicate that.
E.g. the clock image on the Question Page is huge. If page breaks, I don't care. I will put the graphic in there, and put it also in the bulelt list you mentioned (It is already in my comment above) and that's it from my side. Are we good with that?

  2.  I personally do not know the correct dimensions of the graphics.
E.g. for the Clock image above, I will not be the one selecting the dimensions.
And I will not do the job of comparing images' dimensions among them, just in case I find sth that makes sense in order to propose that to the customer.
I think this is clear and agreed too, right?

Please let's agree on the 2 above and the next versions of tha apks will be with whatever graphics provided. There is no back to this though. So, next apk versions might be "ugly"/breaking UI (not sure how it will look like, really) until the correct graphics are provided.

Do you agree with that approach?

**Comment by panagiotissp** [comment]
@ignacioch for the bullet 2, I do not have specific-dimension-missing graphics.
Either I am provided with each xxxhdpi graphic, I take that and pass it through the 9Patch tool which creates all other versions/dimensions, and then I paste all these new images to the corresp folders.

So let's say: Either I have all versions (and all are good or problematic) or I have nothing. So this falls in the 1st bullet.

Let's proceed that way, I will put all graphics on screen or leave it empty, and I will be listing the problems in the description of the current ticket.

If you find graphics that are problematic/missing in the reviews, open separate issues as you already doing. I will review and if I indeed do not have the graphic, I will close that issue and put the missing things on the description here.

**Comment by ignacioch** [comment]
got it but not sure what I need to request.

Maybe I can start with something like - 'graphics for clock' and hope they send us the correct one. Let's start listing them - only one way to find out :)


Sent from Outlook<http://aka.ms/weboutlook>


________________________________

**Comment by ignacioch** [comment]
Ok can you please try those that they send me : 

It includes : 

- clock image
- the images for the popup
- the selected/unselected 10 rounds.

I think the selected 10 rounds is wrong - can you let me know the correct dimension? They probably need to cut in a different frame because they send it with too many space ( unless the others are the same as well ).

Also I am not sure but I assume these dimensions they send are for xxxhdpi ( again my assumption from one of the psd's they send ).

https://www.dropbox.com/sh/m53qzelqb8wyc3n/AABzqtzew2eILW3ZspdyvH0ga?dl=0

**Comment by panagiotissp** [comment]
Closing this since all the rest of missing/problematic graphics will be handled under #67
