### ISSUE TITLE
[Sudden Death Page] Flow from score page to Sudden death page

### ISSUE THREAD

**Issue by panagiotissp** [labooltd/GameAndroid#36]
@ignacioch  based on your screenshots on issue #35 I am confused about the flow to be implemented:

Senario: 
We are on Questions page for last team on last round.
The answers just found make the game a tie between team 1 and team 4 (i.e. drive the game into sudden death)

So:
- On clicking 'next' on this last Question page, I currently show the popup mode of Sudden death page, i.e. a popup is shown, only the teams participating in sudden death are shown, no animation is shown. Are all these correct?
Based on your screenshot https://www.dropbox.com/s/ny1lflrkcbqyppk/Photo%2007-10-2017%2C%2014%2011%2030.png?dl=0 it is not since you include there all teams.
However, your implementation is opposite to the specs provided to me (screenshot below):
![specs-popup-mode](https://user-images.githubusercontent.com/14311142/31319957-0f98bfb0-ac75-11e7-84bc-b74350709a14.PNG)

 
- On the next Sudden death page, only the teams played should be shown (as normal), no popup should be shown (as normal) and a number of rounds should be shown, using the 'death' image and the number of rounds as exponent (screenshot below):
![specs-after-popup-mode](https://user-images.githubusercontent.com/14311142/31319969-3cf07bba-ac75-11e7-92ed-0e95440fee04.PNG)
However, your implementation shown on this screenshot https://www.dropbox.com/s/ek0yahx7nuymike/Photo%2007-10-2017%2C%2014%2011%2051.png?dl=0
is not aligned with that.

Could you please clarify? (A video would probably be the best solution if it is easy enough)

**Comment by ignacioch** [comment]
Yes please follow the latest ones - this is what happens on IOS and clients have not requested a change. I can prepare a video this evening as well.

To sum up : 

- On clicking 'next' on this last Question page, I currently show the popup mode of Sudden death page, i.e. a popup is shown, no animation, WITH ALL THE TEAMS. 

( if it's a big change for you, you can leave it and I can communicate with clients, but I prefer to be identical ). Let me know how overhead this is.

- On the next Sudden death page, only the teams played should be shown (as normal), no popup should be shown (as normal) and a number of rounds should be shown, ---> rounds continue counting like 6/6 etc.

Again if a big overhead, let me know.

PS2 : The screenshots you send above are the very first specs, for a reason that I can't remember at the moment were not implemented and clients didn't request that change, so since IOS is "approved" by them I would keep IOS and Android identical.

**Comment by panagiotissp** [comment]
The first part should not be difficult as I think of it.
The second part of showing the 'Round 6/6' text should be a little more challenging since I think I do not keep the info of the initial number of rounds in my implementation.

I will change that though in order to be aligned with the approved version of iOS.

**Comment by ignacioch** [comment]
But you should have them - user select total number of rounds. and then you need that to : 

1. determine if it's the last round or not
2. display the 3 / 5 text

not sure how you have implemented that but this should be a variable somewhere.

**Comment by panagiotissp** [comment]
For future reference for me:
Activities were UI logic changed for showing number for Sudden death counter 'Round 6/6' case:
- GoActivity
- ScoresActivity
- SuddenDeathActivity
- PlayerAskingQuestionActivity
- PlayerAnsweringQuestionActivity

**Comment by panagiotissp** [comment]
Closed by commit [8b5d972](https://github.com/labooltd/GameAndroid/commit/8b5d9720bb70b2e62fe640f8cec420546cf0e9d3)
