### ISSUE TITLE
[Store Page] home button does not work

### ISSUE THREAD

**Issue by ignacioch** [labooltd/GameAndroid#4]
-

**Comment by panagiotissp** [comment]
Store page is accessible either by main menu page or jokers pop-up (**if this exists at all, I have asked if this should actually be implemented since you had told me at some point that no, probably it should not**).

If accessed by main menu page, there is nothing to be saved, no game.
If accessed from jokers popup then it means that either is the 1st round and first team playing, so nothing to be saved again (no game state exists), or it is accessed **after** a score page had been shown where the save occurred, so nothing to save again.

So, from the above statements, in store page, I have to just return to main screen, without saving anything.
Can you confirm this or tell me what I'm not losing?

**Comment by ignacioch** [comment]
Ok disregard the description :

Home button on Store page should just take as back to main screen. No it doesnt do anything. How home button works in the game, is described in issue #10

**Comment by panagiotissp** [comment]
Done (commit https://github.com/labooltd/GameAndroid/commit/d368c296fc6cac08dca09e9877d13f36496fc3b2 )
