### ISSUE TITLE
[Options] Sound on/off makes screen go up and down

### ISSUE THREAD

**Issue by ignacioch** [labooltd/GameAndroid#6]
Ok you mentioned that we need more graphics for this one :
- can you comment here which ones do we need and I will request them.

**Comment by panagiotissp** [comment]
As I wrote in our private conversation, there are missing graphics for this page (which causes this issue) but there are also more graphics that are needed and this is very important in general, since it affects distances among elements, possible 'small movements' of elements when events are triggered, as in the current issue.
Should I open a new issue and put all of them there instead of putting only some of them here?
