### ISSUE TITLE
Fonts.

### ISSUE THREAD

**Issue by ignacioch** [labooltd/GameAndroid#87]
Download the fonts from here : https://github.com/labooltd/GameOd/tree/master/GameOd/Fonts

Did you have those?

Also, can we double check from the excel that we are using the correct font and size?

[App text final.xlsx (2).xlsx](https://github.com/labooltd/GameAndroid/files/1480522/App.text.final.xlsx.2.xlsx)

**Comment by panagiotissp** [comment]
@ignacioch as we discussed in person, this had already been done by me under the scope of #66 
If customer has an issue with the fonts probably the provided values are problematic.
But since it might always be the case I missed sth, I should have something more specific reported (which page, which text is problematic) in order to double check

Assigning to you based on our discussion, you will makea quick comparison with iOS and update me here.

**Comment by panagiotissp** [comment]
Also this excel **does not** have font sizes.... When I checked the whole thing on task #66 it took me like 3 hours in which I also created this document:

https://docs.google.com/spreadsheets/d/197S7yDC2TKdD9xhyIm_hekyksvlVhiRDmTeIaIVglhs/edit?usp=sharing

It merges actually the one you provided above, which is the same that you had provided on that issue in the near past, *plus* the excel I had that included the fonts

**Comment by ignacioch** [comment]
if the store is fixed the rest look ok - i will check on the final apk as well.
