### ISSUE TITLE
Jokers and FootMode Popup.

### ISSUE THREAD

**Issue by ignacioch** [labooltd/GameAndroid#97]
You are not going to like that but : 
> Joker pop-up and football pop-up issues: We do not feel that the Jokers or the Foot mode text is a title, it should be centered and slightly bigger(or bold) than the main body text. Also, I do not know if it is possible, but we would like the pop-up to appear like in iOS in the middle and not at the bottom of the screen

They mean they don't want the toast but a dialog box with an OK at the bottom. How easy is to change? is it boilerplate code that you just copy paste?

**Comment by panagiotissp** [comment]
@ignacioch 
Is this ok?
![jokers-popup](https://user-images.githubusercontent.com/14311142/32991134-6dc201ac-cd3e-11e7-817a-6e889250a4b6.PNG)
![foot-popup](https://user-images.githubusercontent.com/14311142/32991135-6ddfdbd2-cd3e-11e7-9174-2a39b1728893.PNG)

Please confirm since I do not want to change this thing again....

Also, one extra question:
 Jokers help popup opens in **all** cases (noJokersVersion, JokersVersion+jokers locked, JokersVersion+jokers unlocked).. right?

Please confirm the above to be 100% sure we are aligned

**Comment by panagiotissp** [comment]
We confirmed in person that this is the wanted popup, so closed the issue
